services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    build:
      context: .
      args:
        DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/postgres"
        RUST_LOG: "info"
    ports:
      - "7878:7878"
    depends_on:
      postgres:
        condition: service_healthy
